#! /bin/bash

folder_name=spack_test
branch_name=integrate/develop

#946 --> intel compiler install          https://github.com/LLNL/spack/pull/946
#869 --> add views command               https://github.com/LLNL/spack/pull/869
#943 --> config ure compilers env vars   https://github.com/LLNL/spack/pull/943
#984 --> modules files suffixes          https://github.com/LLNL/spack/pull/984
#820 --> qt 5.6 ( OSX ?)                 https://github.com/LLNL/spack/pull/820
#797 --> cmake gui separate package      https://github.com/LLNL/spack/pull/797
#579 --> cache downloads                 https://github.com/LLNL/spack/pull/579
#378 --> dependency types                https://github.com/LLNL/spack/pull/378

pr_to_integrate="946 579 869 984 797"
branches_to_integrate="local/modules pr/fix/boost_intel pr/intel/fix_openmpi pr/fix_gmp virtualgl wip/vtk"

cd deploy

git clone -b clean/develop https://github.com/RemoteConnectionManager/spack.git ${folder_name}
cd ${folder_name}
git remote add upstream https://github.com/LLNL/spack
#git pull --ff-only upstream develop

git checkout -b ${branch_name}
git fetch origin clean/develop:clean/develop

for pr in ${pr_to_integrate} ; do  
  echo "integrating PR $pr"
  git fetch upstream pull/${pr}/head:pull/${pr}/clean
  git checkout pull/${pr}/clean
  git checkout -b pull/${pr}/update
  git merge -m "sync to develop" clean/develop
  git checkout ${branch_name}
  git merge -m "merge pr ${pr}" pull/${pr}/update
done
  
for br in ${branches_to_integrate} ; do
  git checkout ${br}
  #git pull --rebase origin clean/develop
  #git pull --ff-only
  git merge --ff-only clean/develop
  git checkout ${branch_name}
  git merge -m "merge branch ${br}" ${br}
done
