#! /bin/bash
source share/spack/setup-env.sh
spack  config --site  get bad_section_name

#add system compiler
spack  compiler find --scope site    
#print what has been found
spack  config --site  get compilers

#add our our package repo folder
spack repo add ../../repo --scope site
#print what has been added
spack  config --site  get repos

#list all available packages   
spack list
