#! /bin/bash
# Absolute path to this script. /home/user/bin/foo.sh

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export RCM_DEPLOY_HOSTPATH="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source ../../get_root
export RCM_DEPLOY_SPACKPATH=${PWD}
#echo "setting up spach work copy in ${RCM_DEPLOY_SPACKPATH} config in ${RCM_DEPLOY_HOSTPATH}/config root in ${RCM_DEPLOY_ROOTPATH}"

source ${RCM_DEPLOY_SPACKPATH}/share/spack/setup-env.sh
