config:
  plugin_folders:
    - 'plugins/git_workspace'
    - 'plugins/spack_workspace'

  config_folders:
#    - 'test/overload/defaults.yaml'
    - 'spack/devel'
    - 'rcm'
    - 'rcm/server'
#    - insitu
