#! /bin/bash
# Absolute path to this script. /home/user/bin/foo.sh

echo "setting up spack work copy in ${RCM_DEPLOY_SPACKPATH} config in ${RCM_DEPLOY_HOSTPATH}/config root in ${RCM_DEPLOY_ROOTPATH}"

for filename in ${RCM_DEPLOY_HOSTPATH}/config/*.yaml; do
  config_file="${RCM_DEPLOY_SPACKPATH}/etc/spack/$(basename "$filename")"
  echo "creating config ${config_file} from $filename"
  envsubst < ${filename} '${RCM_DEPLOY_SPACKPATH} ${RCM_DEPLOY_HOSTPATH} ${RCM_DEPLOY_ROOTPATH} ${USER}' > ${config_file}
done
spack repo add ${RCM_DEPLOY_ROOTPATH}/repo --scope site

#add system compiler
spack  compiler find --scope site    
#print what has been found
spack  config --scope site  get compilers

exit
#add site specific module configuration
cp ${ROOTPATH}/config/modules.yaml etc/spack

#symbolic link to cache folder
mkdir -p ${ROOTPATH}/cache
rm -f var/spack/cache
ln -s ${ROOTPATH}/cache var/spack

#add our our package repo folder
spack repo add ${ROOTPATH}/repo --scope site
#print what has been added
spack  config --scope site  get repos

#list all available packages   
spack list

#make a view for rcm
spack install rcm@develop xeyes xdpyinfo xconsole xcalc fluxbox
spack view symlink ${ROOTPATH}/deploy/views/rcm xeyes xdpyinfo xconsole xcalc fluxbox turbovnc rcm
