# this is


defaults:
  integration : 'True'
  clearconfig : 'True'
  origin :
    master : 'integrate/insitu'
    branches :
      - 'packages/mesa-headless-opengl'
      - 'pr/fix-qt5-opengl'
      - 'packages/qt5-headless-opengl'
      - 'packages/qt5-dbus'
      - 'packages/qt5-virtualgl'
      - 'packages/update_paraview'
  upstream :
    prs :
      - '8070'







