compilers:
- compiler:
    environment: {}
    extra_rpaths: 
    - /cineca/prod/compilers/intel/pe-xe-2017/binary/lib/intel64
    flags: {}
    modules: [intel/pe-xe-2017--binary]
    operating_system: centos7
    paths:
      cc: /galileo/prod/compilers/intel/pe-xe-2017/binary/bin/icc
      cxx: /galileo/prod/compilers/intel/pe-xe-2017/binary/bin/icpc
      f77: /galileo/prod/compilers/intel/pe-xe-2017/binary/bin/ifort
      fc: /galileo/prod/compilers/intel/pe-xe-2017/binary/bin/ifort
    spec: intel@17.0.0
    target: x86_64
