packages:

  openssl:
    paths:
      openssl@1.0.2g: /usr
    buildable: False

  slurm:
    paths:
      slurm@17.11.7 : /usr/ 
    buildable : False

  openmpi:
    variants:
    - fabrics=verbs,psm
    - +legacylaunchers
    - schedulers=slurm
    - +pmi
    version:
    - 3.1.3

# from Eric setup
  intel-mpi:
    modules:
      intel-mpi@2018.2.199%gcc@7.3.0 arch=linux-centos7-x86_64: intelmpi/2018--binary
      buildable: False
  
  intel-mkl:
    modules:
      intel-mkl@2018.2.199%gcc@7.3.0 arch=linux-centos7-x86_64: mkl/2018--binary
      buildable: False  


# opengl hack.... check version
  opengl:
    paths:
      opengl@4.5.0: /cineca/prod/spack/v001/prefix_gl_devel

  all:
    compiler: [gcc@4.8.2, gcc@7.3.0]
    providers:
      mpi: [openmpi, intelmpi]
      
