packages:

  openssl:
    version:
    - 1.0.2g
  qt:
    version:
    - 5.10.0


#    paths:
#      openssl@1.0.2g: /usr
#    buildable: False

  slurm:
    paths:
      slurm@17.11.7 : /usr/ 
    buildable : False

  openmpi:
    variants:
    - fabrics=verbs,psm2
    - +legacylaunchers
    - schedulers=slurm
    - +pmi
    version:
    - 3.1.3

# from Eric setup
# Removed, as it override dependencies when %gcc@7.3.0 as per hdf5
#  intel-mpi:
#    modules:
#      intel-mpi@2018.2.199%gcc@7.3.0 arch=linux-centos7-x86_64: intelmpi/2018--binary
#      buildable: False
  
#  intel-mkl:
#    modules:
#      intel-mkl@2018.2.199%gcc@7.3.0 arch=linux-centos7-x86_64: mkl/2018--binary
#      buildable: False  


# opengl hack.... check version
  opengl:
    paths:
      opengl@4.5.0: "@{RCM_DEPLOY_HOSTPATH}/external_packages/opengl"
    buildable: False
  openglu:
    paths:
      openglu@1.3: "@{RCM_DEPLOY_HOSTPATH}/external_packages/opengl"
    buildable: False

  all:
    compiler:
    - gcc@4.8.2
    - gcc@4.8.5
    - gcc@6.1.0
    - gcc@7.3.0
    - intel@18.0.5
      
