packages:
  qt:
    compiler: [gcc@4.8.2]
    variants: +examples
    version: [4.8.6, 5.7.0]
  mesa:
    compiler: [gcc@4.8.2]
    variants: +gallium
  pango:
    variants: +X
  gtkplus:
    variants: +X
  cairo:
    variants: +X
  all:
    compiler: [gcc@4.8.2, gcc@4.9.2]

