packages:
  openmpi:
    variants:
    - fabrics=psm
    - schedulers=slurm
    - +pmi
    version:
    - 3.0.1
#to_check    buildable: False
#to_check    variants:
#to_check    - schedulers=tm
  intelmpi:
    modules:
      intelmpi@2017%intel@17.0.0: intelmpi/2017--binary
    buildable: False
  opengl:
    paths:
      opengl@4.5.0: /cineca/prod/spack/v001/prefix_gl_devel
  all:
    compiler: [gcc@7.3.0, gcc@4.8.2]
    providers:
      mpi: [openmpi, intelmpi]
      
