#!/bin/bash

#PBS -l select=1:ncpus=24:mem=40gb
#PBS -l walltime=01:58:00

#PBS -A cin_priorit

#PBS -N BS -N build_rcm
#PBS -V

export LOGFILE=${PBS_O_WORKDIR}/log_build.${PBS_JOBID}.log
source /marconi_work/cin_prc5wp62/spack/insitu/deploy/insitu/05/spack/share/spack/setup-env.sh
spack install  --keep-stage --verbose qt   > ${LOGFILE}  2>&1
spack install  --keep-stage --verbose paraview+qt+python   > ${LOGFILE}  2>&1


